# Generated by Django 4.1.7 on 2023-07-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_blog', models.CharField(max_length=100, verbose_name='Заголовок блога')),
                ('description_blog', models.CharField(max_length=250, verbose_name='')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Дата')),
            ],
        ),
    ]
