# Generated by Django 4.1.7 on 2023-07-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_time_blog_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='description_blog',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
    ]
