# Generated by Django 4.1.7 on 2023-07-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_options_alter_blog_description_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description_blog',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
